from pydantic import BaseModel, Field
from typing import Optional

class Candidate(BaseModel):
    name: str = Field(..., description="The candidate's full name")
    email: str = Field(..., description="The candidate's email address")
    phone: str = Field(..., description="The candidate's phone number")
    location: Optional[str] = Field(None, description="The candidate's location")
    linkedin: Optional[str] = Field(None, description="The candidate's LinkedIn profile URL")
    GitHub: Optional[str] = Field(None, description="The candidate's GitHub profile URL")
    portfolio: Optional[str] = Field(None, description="The candidate's portfolio URL")

class Skills(BaseModel):
    programming_languages: Optional[list[str]] = Field(None, description="List of programming languages known by the candidate")
    frameworks: Optional[list[str]] = Field(None, description="List of frameworks known by the candidate")
    Databases: Optional[list[str]] = Field(None, description="List of databases known by the candidate")
    cloud_platforms: Optional[list[str]] = Field(None, description="List of cloud platforms known by the candidate")
    devops_tools: Optional[list[str]] = Field(None, description="List of DevOps tools known by the candidate")
    ai_ml_tools: Optional[list[str]] = Field(None, description="List of AI/ML tools known by the candidate")
    soft_skills: Optional[list[str]] = Field(None, description="List of soft skills possessed by the candidate")

class Education(BaseModel):
    degree: Optional[str] = Field(None, description="The degree obtained by the candidate")
    institution: Optional[str] = Field(None, description="The educational institution attended by the candidate")
    graduation_year: Optional[int] = Field(None, description="The year of graduation")

class Experience(BaseModel):
    company: Optional[str] = Field(None, description="The company where the candidate worked")
    role: Optional[str] = Field(None, description="The role or position held by the candidate")
    start_date: Optional[str] = Field(None, description="The start date of the employment")
    end_date: Optional[str] = Field(None, description="The end date of the employment")
    responsibilities: Optional[list[str]] = Field(None, description="List of responsibilities held by the candidate in the role")

class Project(BaseModel):
    title: Optional[str] = Field(None, description="The title of the project")
    description: Optional[str] = Field(None, description="A brief description of the project")
    technologies_used: Optional[list[str]] = Field(None, description="List of technologies used in the project")
    link: Optional[str] = Field(None, description="A link to the project (if available)")

class Certification(BaseModel):
    name: Optional[str] = Field(None, description="The name of the certification")
    issuing_organization: Optional[str] = Field(None, description="The organization that issued the certification")
    issue_date: Optional[str] = Field(None, description="The date when the certification was issued")
    expiration_date: Optional[str] = Field(None, description="The expiration date of the certification (if applicable)")
    credential_id: Optional[str] = Field(None, description="The unique identifier for the certification")
    credential_url: Optional[str] = Field(None, description="A URL to verify the certification (if available)")

class Achievements(BaseModel):
    title: Optional[str] = Field(None, description="The title of the achievement")
    description: Optional[str] = Field(None, description="A brief description of the achievement")
    date: Optional[str] = Field(None, description="The date when the achievement was accomplished")

class Languages(BaseModel):
    name: Optional[str] = Field(None, description="The name of the language")
    proficiency: Optional[str] = Field(None, description="The proficiency level in the language (e.g., Beginner, Intermediate, Advanced, Fluent)")


class AIAnalysis(BaseModel):
    resume_summary: Optional[str] = Field(None, description="A summary of the candidate's resume generated by AI")
    strengths: Optional[list[str]] = Field(None, description="List of strengths identified in the candidate's resume")
    areas_for_improvement: Optional[list[str]] = Field(None, description="List of areas for improvement identified in the candidate's resume")
    missing_skills: Optional[list[str]] = Field(None, description="List of skills that are missing or could be beneficial for the candidate to acquire")
    suggested_job_roles: Optional[list[str]] = Field(None, description="List of job roles that are suitable for the candidate based on their resume analysis")
    resume_score: Optional[float] = Field(None, description="A score representing the overall quality of the candidate's resume based on AI analysis")
    experience_level: Optional[str] = Field(None, description="The experience level of the candidate based on their resume analysis (e.g., Entry-level, Mid-level, Senior-level)")


class ResumeAnalysis(BaseModel):
    candidate: Candidate = Field(..., description="The candidate's personal information")
    skills: Skills = Field(..., description="The candidate's skills and proficiencies")
    education: list[Education] = Field(..., description="The candidate's educational background")
    experience: Optional[list[Experience]] = Field(None, description="The candidate's work experience")
    projects: Optional[list[Project]] = Field(None, description="The candidate's projects and contributions")
    certifications: Optional[list[Certification]] = Field(None, description="The candidate's certifications and credentials")
    achievements: Optional[list[Achievements]] = Field(None, description="The candidate's notable achievements and awards")
    languages: Optional[list[Languages]] = Field(None, description="The languages known by the candidate and their proficiency levels")
    ai_analysis: AIAnalysis = Field(..., description="AI-generated analysis of the candidate's resume")
